  server:
    port: 80
  spring:
    application:
    name: JIminShop

    devtools:
      livereload:
        enabled: true # 화면 갱신
      restart:
        enabled: true # 재시작

    thymeleaf:
      cache: false # 캐시 안함

    #MYSQL 설정
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring_a
      username: root
      password: 12341234

    jpa:
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      show-sql: true
      properties:
        hibernate:
          format_sql: true

      database-platform: org.hibernate.dialect.MySQL8Dialect

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace
